import { ImpactCategory } from './types';

// ──────────────────────────────────────────────
// Heuristic Baselines
//
// Each inference maps to a baseline percentage impact range.
// These are conservative, industry-grounded heuristics.
// They produce the percentage_delta; the estimation engine
// scales them by business inputs to produce absolute $.
// ──────────────────────────────────────────────

export interface BaselineEntry {
  inference_key: string;
  impact_category: ImpactCategory;
  cause: string;
  effect: string;

  // Percentage ranges by severity
  high: { min: number; max: number };    // % of revenue/rate
  medium: { min: number; max: number };
  low: { min: number; max: number };

  // What this percentage applies to
  base_metric: 'revenue' | 'transactions' | 'chargeback_rate' | 'conversion_rate';
}

export const IMPACT_BASELINES: Record<string, BaselineEntry> = {
  // ── Scale readiness ──────────────────────────
  trust_boundary_crossed: {
    inference_key: 'trust_boundary_crossed',
    impact_category: 'conversion_loss',
    cause: 'Checkout trust continuity broken',
    effect: 'Users abandon conversion when redirected to unknown domains — trust breaks at the purchase moment directly reduce checkout completion',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  policy_gap: {
    inference_key: 'policy_gap',
    impact_category: 'conversion_loss',
    cause: 'Consumer protection policies missing or incomplete',
    effect: 'Buyers hesitate when privacy, terms, or refund policies are absent — reduces checkout confidence and increases bounce near payment',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.07 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  checkout_integrity: {
    inference_key: 'checkout_integrity',
    impact_category: 'conversion_loss',
    cause: 'Checkout structural integrity degraded',
    effect: 'Off-domain handoffs, weak policy coverage, and fragile checkout architecture reduce completion rate under traffic',
    high: { min: 0.15, max: 0.35 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  revenue_path_fragile: {
    inference_key: 'revenue_path_fragile',
    impact_category: 'revenue_loss',
    cause: 'Revenue path structurally fragile under scale',
    effect: 'Errors, slow responses, and off-domain redirects on the commercial path cause progressive drop-off that worsens with traffic volume',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  measurement_coverage: {
    inference_key: 'measurement_coverage',
    impact_category: 'traffic_waste',
    cause: 'Measurement infrastructure insufficient for optimization',
    effect: 'Without analytics coverage, ad spend cannot be attributed, conversion funnels cannot be optimized, and revenue leakage remains invisible',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── Revenue integrity ──────────────────────────
  conversion_flow_fragmented: {
    inference_key: 'conversion_flow_fragmented',
    impact_category: 'revenue_loss',
    cause: 'Conversion flow scattered across domains',
    effect: 'Each domain handoff in the checkout path loses 10-30% of users — fragmentation compounds drop-off multiplicatively',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  friction_on_critical_path: {
    inference_key: 'friction_on_critical_path',
    impact_category: 'revenue_loss',
    cause: 'Friction barriers on the revenue path',
    effect: 'Broken forms, slow-loading pages, and excessive redirects on the critical path reduce conversion at every step',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  revenue_leakage: {
    inference_key: 'revenue_leakage',
    impact_category: 'revenue_loss',
    cause: 'Revenue actively leaking from conversion path',
    effect: 'Broken forms, missing conversion paths, and fragmented checkout flow are actively losing completed transactions',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  trust_break_in_checkout: {
    inference_key: 'trust_break_in_checkout',
    impact_category: 'conversion_loss',
    cause: 'Trust signals absent at the purchase moment',
    effect: 'Missing policies, unknown domain handoffs, and weak trust surface at the exact moment of payment cause abandonment',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  measurement_blindspot: {
    inference_key: 'measurement_blindspot',
    impact_category: 'traffic_waste',
    cause: 'Blind spot on commercial page measurement',
    effect: 'Revenue-critical pages have no analytics — leakage is invisible, attribution is broken, and optimization is impossible on the pages that matter most',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  unclear_conversion_intent: {
    inference_key: 'unclear_conversion_intent',
    impact_category: 'conversion_loss',
    cause: 'Primary conversion path unclear to visitors',
    effect: 'Visitors cannot identify the path to purchase — missing CTAs, competing actions, or absent conversion entry points leave purchase intent unresolved',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },

  // ── Chargeback resilience ──────────────────────
  refund_policy_gap: {
    inference_key: 'refund_policy_gap',
    impact_category: 'chargeback_risk',
    cause: 'Refund and return expectations undocumented',
    effect: 'Without a clear refund process, dissatisfied customers bypass the merchant entirely and file chargebacks as their only recourse',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.02 },
    base_metric: 'chargeback_rate',
  },
  support_unreachable: {
    inference_key: 'support_unreachable',
    impact_category: 'chargeback_risk',
    cause: 'Customer support channels invisible or missing',
    effect: 'When customers cannot find a way to contact support, their only option for resolving issues is filing a dispute with their bank',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.05 },
    low: { min: 0.01, max: 0.02 },
    base_metric: 'chargeback_rate',
  },
  expectation_misalignment: {
    inference_key: 'expectation_misalignment',
    impact_category: 'chargeback_risk',
    cause: 'Purchase expectations poorly set before checkout',
    effect: 'Hidden pricing, missing order confirmation, or brand disconnect at checkout create surprise charges — the #1 driver of "unauthorized transaction" disputes',
    high: { min: 0.03, max: 0.10 },
    medium: { min: 0.01, max: 0.04 },
    low: { min: 0.005, max: 0.015 },
    base_metric: 'chargeback_rate',
  },
  dispute_risk_elevated: {
    inference_key: 'dispute_risk_elevated',
    impact_category: 'chargeback_risk',
    cause: 'Compound chargeback risk from multiple deficiencies',
    effect: 'Missing refund policy, unreachable support, broken trust boundaries, and hidden pricing combine to create elevated dispute exposure across every transaction',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },

  // ── SaaS Growth Readiness ──────────────────────

  activation_blocked: {
    inference_key: 'activation_blocked',
    impact_category: 'conversion_loss',
    cause: 'Activation path blocked before first value',
    effect: 'High-complexity steps, MFA walls, or missing prerequisites prevent trial users from ever reaching the product — direct trial-to-paid conversion loss',
    high: { min: 0.15, max: 0.35 },
    medium: { min: 0.08, max: 0.18 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  activation_friction_high: {
    inference_key: 'activation_friction_high',
    impact_category: 'conversion_loss',
    cause: 'Onboarding friction eroding trial-to-paid conversion',
    effect: 'Too many steps, missing progress indicators, and unclear CTAs in onboarding cause progressive user drop-off before activation',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  unclear_next_step: {
    inference_key: 'unclear_next_step',
    impact_category: 'conversion_loss',
    cause: 'Users stranded without clear next action in onboarding',
    effect: 'Onboarding steps lack clear CTAs or progress indicators — users get stuck, time-to-value increases, and first-session churn rises',
    high: { min: 0.08, max: 0.18 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  empty_state_without_guidance: {
    inference_key: 'empty_state_without_guidance',
    impact_category: 'lifetime_value_loss',
    cause: 'Empty screens driving early-session abandonment',
    effect: 'New users encounter blank interfaces with no guidance, sample data, or next-step CTAs — confusion drives immediate churn',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.03, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  navigation_overcomplex: {
    inference_key: 'navigation_overcomplex',
    impact_category: 'lifetime_value_loss',
    cause: 'App navigation burying core features',
    effect: 'Too many items and deep nesting prevent users from discovering features they need — perceived product value drops, engagement falls, retention erodes',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  feature_discovery_poor: {
    inference_key: 'feature_discovery_poor',
    impact_category: 'lifetime_value_loss',
    cause: 'Key features hidden behind complex navigation',
    effect: 'Complex navigation combined with empty states means users never discover core capabilities — they perceive less value and churn',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.07 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  upgrade_invisible: {
    inference_key: 'upgrade_invisible',
    impact_category: 'revenue_loss',
    cause: 'Upgrade surfaces hidden at value moments',
    effect: 'No visible upgrade path in the product — users who would pay cannot discover how, directly limiting expansion revenue',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  upgrade_timing_wrong: {
    inference_key: 'upgrade_timing_wrong',
    impact_category: 'revenue_loss',
    cause: 'Upgrade prompts shown without value context',
    effect: 'Upgrade CTAs appear without explaining what the user gains — conversion to paid suffers because the ask lacks justification',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.09 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  no_expansion_path: {
    inference_key: 'no_expansion_path',
    impact_category: 'revenue_loss',
    cause: 'No self-serve path from free to paid',
    effect: 'No upgrade surfaces or expansion CTAs found — users willing to pay have no mechanism to do so, capping revenue at current tier',
    high: { min: 0.12, max: 0.35 },
    medium: { min: 0.06, max: 0.18 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  landing_app_mismatch: {
    inference_key: 'landing_app_mismatch',
    impact_category: 'conversion_loss',
    cause: 'Landing page promise disconnected from app reality',
    effect: 'Marketing promises simplicity but the product requires complex onboarding — the expectation gap causes first-session churn as users feel misled',
    high: { min: 0.12, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Phase 30: New findings from existing evidence ────

  critical_path_broken: {
    inference_key: 'critical_path_broken',
    impact_category: 'revenue_loss',
    cause: 'Revenue-critical pages returning errors',
    effect: 'Checkout, cart, or pricing pages are unreachable — every visitor hitting these errors is a lost transaction',
    high: { min: 0.15, max: 0.40 },
    medium: { min: 0.08, max: 0.20 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  form_data_leaves_domain: {
    inference_key: 'form_data_leaves_domain',
    impact_category: 'conversion_loss',
    cause: 'Buyer data leaving the domain through unrecognized form targets',
    effect: 'Forms send data to untrusted third-party endpoints — trust break at submission point reduces completion rate',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  checkout_provider_fragmented: {
    inference_key: 'checkout_provider_fragmented',
    impact_category: 'conversion_loss',
    cause: 'Checkout fragmented across competing payment providers',
    effect: 'Multiple provider scripts create inconsistent checkout UX, increasing cognitive load and abandonment',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.07 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },

  // ── Phase 30B: Extended findings from existing evidence ────

  redirect_chain_erodes_checkout_trust: {
    inference_key: 'redirect_chain_erodes_checkout_trust',
    impact_category: 'conversion_loss',
    cause: 'Checkout trust eroded by multi-hop redirect chain',
    effect: 'Each domain-crossing redirect on the path to payment loses 5-15% of buyers — trust erodes progressively with each hop',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  commercial_journey_language_break: {
    inference_key: 'commercial_journey_language_break',
    impact_category: 'conversion_loss',
    cause: 'Commercial journey switches language before conversion',
    effect: 'Language change between browsing and checkout creates confusion and distrust — buyers abandon when payment surfaces speak a different language',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  commercial_pages_disconnected: {
    inference_key: 'commercial_pages_disconnected',
    impact_category: 'revenue_loss',
    cause: 'Commercial pages disconnected from main conversion journey',
    effect: 'Checkout, pricing, or billing pages exist but have no navigation path from the main site — visitors cannot discover how to purchase',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  untrusted_embeds_near_purchase: {
    inference_key: 'untrusted_embeds_near_purchase',
    impact_category: 'conversion_loss',
    cause: 'Unknown external embeds on purchase surfaces',
    effect: 'Unrecognized third-party iframes on checkout and payment pages undermine buyer trust — unlike Stripe or PayPal embeds, these create suspicion',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  platform_checkout_risk_unaddressed: {
    inference_key: 'platform_checkout_risk_unaddressed',
    impact_category: 'conversion_loss',
    cause: 'Platform-specific checkout configuration creating unresolved risk',
    effect: 'The detected platform has checkout patterns that are misconfigured or underprotected — off-domain checkout on native platforms, or missing policies on hosted checkout flows',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  post_purchase_confirmation_absent: {
    inference_key: 'post_purchase_confirmation_absent',
    impact_category: 'chargeback_risk',
    cause: 'Post-purchase confirmation and refund terms both absent',
    effect: 'No order confirmation page and no return policy — customers who just paid cannot verify their order or understand recourse, driving "unauthorized charge" disputes',
    high: { min: 0.06, max: 0.15 },
    medium: { min: 0.03, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },
  high_intent_surfaces_blind: {
    inference_key: 'high_intent_surfaces_blind',
    impact_category: 'traffic_waste',
    cause: 'High-intent surfaces operating without optimization visibility',
    effect: 'Analytics present sitewide but missing on checkout and payment pages — the pages that generate revenue cannot be measured, attributed, or optimized',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  revenue_path_regressed: {
    inference_key: 'revenue_path_regressed',
    impact_category: 'revenue_loss',
    cause: 'Revenue path degraded since last audit',
    effect: 'Previously stable or healthy commercial path decisions have worsened — this is a confirmed regression, not a first-time finding',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },

  // ── Phase 2: Findings from deepened collection ────

  refund_terms_too_thin: {
    inference_key: 'refund_terms_too_thin',
    impact_category: 'chargeback_risk',
    cause: 'Refund and return terms too thin to defuse disputes',
    effect: 'A refund policy too brief to explain return windows, processes, or exceptions — dissatisfied customers bypass the merchant and file chargebacks',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },
  support_hidden_at_purchase: {
    inference_key: 'support_hidden_at_purchase',
    impact_category: 'conversion_loss',
    cause: 'Support exists but hidden when buyers need reassurance',
    effect: 'Live chat available on the site but absent from checkout — hesitant buyers with questions about shipping, sizing, or returns abandon instead of asking',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  trust_surface_too_thin: {
    inference_key: 'trust_surface_too_thin',
    impact_category: 'conversion_loss',
    cause: 'Commercial trust signals too thin on high-intent surfaces',
    effect: 'Insufficient trust-building signals (business identity, reviews, policies, recognized providers) — checkout abandonment increases when buyers cannot verify legitimacy',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  tracking_stack_gaps: {
    inference_key: 'tracking_stack_gaps',
    impact_category: 'traffic_waste',
    cause: 'High-intent tracking stack incomplete where optimization matters',
    effect: 'Missing analytics or tag management infrastructure prevents conversion measurement, attribution, and data-driven optimization',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  consent_undermining_measurement: {
    inference_key: 'consent_undermining_measurement',
    impact_category: 'traffic_waste',
    cause: 'Consent and tracking setup undermining measurement continuity',
    effect: 'Consent manager blocks analytics for consenting visitors because no tag manager mediates consent-aware firing — conversion data silently drops',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },

  // ── Phase 2B: Mobile & runtime findings ────

  mobile_commercial_path_blocked: {
    inference_key: 'mobile_commercial_path_blocked',
    impact_category: 'revenue_loss',
    cause: 'Mobile navigation blocking access to commercial paths',
    effect: 'Mobile visitors cannot reach checkout, pricing, or conversion pages — the revenue path does not exist for the majority of traffic',
    high: { min: 0.15, max: 0.35 },
    medium: { min: 0.08, max: 0.18 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  mobile_trust_weaker_than_desktop: {
    inference_key: 'mobile_trust_weaker_than_desktop',
    impact_category: 'conversion_loss',
    cause: 'Mobile buyers routed into weaker trust experience than desktop',
    effect: 'Trust indicators, policies, or provider signals visible on desktop are absent on mobile — mobile buyers see fewer reasons to trust and abandon at higher rates',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  runtime_errors_interrupt_purchase: {
    inference_key: 'runtime_errors_interrupt_purchase',
    impact_category: 'revenue_loss',
    cause: 'Runtime failures interrupting the purchase journey',
    effect: 'JavaScript errors in payment SDK, checkout flow, or transaction logic actively prevent buyers from completing purchases',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  runtime_measurement_broken: {
    inference_key: 'runtime_measurement_broken',
    impact_category: 'traffic_waste',
    cause: 'Runtime failures weakening measurement on high-intent paths',
    effect: 'Analytics and tracking scripts fail at execution time on commercial pages — the site appears instrumented but conversion data is silently dropping',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  secondary_flows_bypass_trust_path: {
    inference_key: 'secondary_flows_bypass_trust_path',
    impact_category: 'revenue_loss',
    cause: 'Secondary commercial flows bypassing main trust path',
    effect: 'Alternate checkout entry points route buyers through paths that escape the main trust, support, and measurement envelope — revenue with reduced protection',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },

  // ── Phase 2C: Split policy and post-purchase findings ────

  refund_process_unclear: {
    inference_key: 'refund_process_unclear',
    impact_category: 'chargeback_risk',
    cause: 'Refund process too vague to defuse post-purchase panic',
    effect: 'Policy page exists but lacks return window, refund steps, or contact info for returns — customers who need resolution cannot find it, and file chargebacks instead',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },
  post_purchase_proof_too_weak: {
    inference_key: 'post_purchase_proof_too_weak',
    impact_category: 'chargeback_risk',
    cause: 'Post-purchase proof too weak to prevent disputes',
    effect: 'Order confirmation page exists but is too thin to serve as purchase proof — buyers cannot verify what they ordered, when it ships, or what to expect, driving "unauthorized" and "not received" disputes',
    high: { min: 0.03, max: 0.10 },
    medium: { min: 0.01, max: 0.05 },
    low: { min: 0.005, max: 0.02 },
    base_metric: 'chargeback_rate',
  },

  // ── Phase 2C: Composite findings ────

  support_reassurance_too_late: {
    inference_key: 'support_reassurance_too_late',
    impact_category: 'conversion_loss',
    cause: 'Support reassurance appears too late in the buying journey',
    effect: 'Help and support exist but are not accessible from commercial pages — hesitant buyers leave the purchase flow to find help and do not return',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  reassurance_routes_disconnected: {
    inference_key: 'reassurance_routes_disconnected',
    impact_category: 'conversion_loss',
    cause: 'Reassurance routes disconnected from the commercial journey',
    effect: 'Help, FAQ, confirmation, and warranty pages exist but have no navigation links from the buying path — the investment in reassurance content is wasted',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  alternate_flows_unmeasured: {
    inference_key: 'alternate_flows_unmeasured',
    impact_category: 'traffic_waste',
    cause: 'Alternate commercial flows operating without measurement',
    effect: 'Some commercial pages lack analytics while others have it — revenue through untracked paths is invisible to attribution and optimization',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  runtime_breaking_reassurance: {
    inference_key: 'runtime_breaking_reassurance',
    impact_category: 'conversion_loss',
    cause: 'Runtime failures breaking support and reassurance at hesitation moments',
    effect: 'Chat widgets, support tools, or consent managers fail at runtime on commercial pages — buyers lose their reassurance channel at the moment they need it most',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  checkout_provider_path_weak: {
    inference_key: 'checkout_provider_path_weak',
    impact_category: 'conversion_loss',
    cause: 'Checkout sending buyers through a weaker-than-expected provider path',
    effect: 'Payment handoff goes to an external domain without recognized provider branding or trust reinforcement — buyers expect Stripe/PayPal-level confidence and do not get it',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.01, max: 0.05 },
    base_metric: 'revenue',
  },
  trust_and_measurement_both_absent: {
    inference_key: 'trust_and_measurement_both_absent',
    impact_category: 'revenue_loss',
    cause: 'Trust and measurement both absent on commercial paths',
    effect: 'Commercial routes operate without trust infrastructure (policies, identity) AND without measurement coverage (analytics) — conversion is weak and the business cannot see why',
    high: { min: 0.12, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Phase 3A: Channel integrity / abuse exposure ────

  payment_surface_compromised: {
    inference_key: 'payment_surface_compromised',
    impact_category: 'revenue_loss',
    cause: 'Purchase surface exposed to unauthorized script influence',
    effect: 'Script injection or missing controls on checkout pages enable formjacking, payment data interception, and session hijack — every transaction carries active fraud exposure',
    high: { min: 0.15, max: 0.40 },
    medium: { min: 0.08, max: 0.20 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  channel_traffic_divertible: {
    inference_key: 'channel_traffic_divertible',
    impact_category: 'traffic_waste',
    cause: 'Customer traffic routed through weakly governed channel surfaces',
    effect: 'Open redirects and permissive cross-origin policies allow attackers to use the brand domain to route buyers to phishing or malicious destinations',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  commerce_operations_exposed: {
    inference_key: 'commerce_operations_exposed',
    impact_category: 'revenue_loss',
    cause: 'Public-facing operational surfaces threatening commerce continuity',
    effect: 'Exposed admin panels, debug endpoints, or configuration files enable pricing manipulation, checkout disruption, data extraction, or forced downtime',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  traffic_landing_low_trust_posture: {
    inference_key: 'traffic_landing_low_trust_posture',
    impact_category: 'conversion_loss',
    cause: 'Paid traffic landing inside a low-trust technical posture',
    effect: 'Browser warnings, missing padlock, or "not secure" indicators suppress conversion before the buyer reads the offer — wasting media spend',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  channel_compromise_visible: {
    inference_key: 'channel_compromise_visible',
    impact_category: 'conversion_loss',
    cause: 'Commercial channel exposed to compromise patterns that trigger distrust',
    effect: 'Multiple simultaneous exposure types signal a channel not hardened for commercial operation — enough to trigger distrust from buyers, partners, and compliance reviewers',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  commercial_path_abuse_friendly: {
    inference_key: 'commercial_path_abuse_friendly',
    impact_category: 'revenue_loss',
    cause: 'Commercial path exposed to abuse-friendly technical conditions',
    effect: 'Unauthenticated APIs, schema exposure, or unprotected business-logic surfaces enable automated fraud, pricing abuse, coupon gaming, and inventory manipulation',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  economic_exploitation_active: {
    inference_key: 'economic_exploitation_active',
    impact_category: 'revenue_loss',
    cause: 'Commerce exposed to systematic economic exploitation',
    effect: 'Cart manipulation, coupon enumeration, or refund fraud endpoints enable automated margin theft — bots modify prices, brute-force discount codes, or initiate fraudulent refunds at scale',
    high: { min: 0.08, max: 0.25 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  checkout_trust_brittle_infrastructure: {
    inference_key: 'checkout_trust_brittle_infrastructure',
    impact_category: 'conversion_loss',
    cause: 'Checkout trust anchored to brittle public infrastructure',
    effect: 'Payment integrity exposures combined with trust posture weaknesses on the same domain — checkout is both vulnerable to compromise and provides no defense-in-depth. Scaling traffic amplifies both fraud and trust failure.',
    high: { min: 0.12, max: 0.35 },
    medium: { min: 0.06, max: 0.18 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },

  // ── Phase 3B: Deep discovery findings ────

  promotion_logic_exposed: {
    inference_key: 'promotion_logic_exposed',
    impact_category: 'revenue_loss',
    cause: 'Promotion logic exposed to abusive discount behavior',
    effect: 'Discoverable coupon, discount, and promo routes enable automated code enumeration, discount stacking, and promotional abuse — directly reducing margin on every exploited transaction',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  cart_variant_weak_control: {
    inference_key: 'cart_variant_weak_control',
    impact_category: 'revenue_loss',
    cause: 'Cart variants allow weaker pricing controls',
    effect: 'Multiple cart/checkout variants carry inconsistent pricing validation — the weakest path determines the actual price floor for automated abuse, enabling price manipulation and inventory gaming',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  hidden_discount_refund_route: {
    inference_key: 'hidden_discount_refund_route',
    impact_category: 'revenue_loss',
    cause: 'Hidden discount or refund routes weaken commercial safeguards',
    effect: 'Discount and refund endpoints outside the intended safeguard model enable automated margin theft from the discount side and fraudulent loss recovery from the refund side',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  guessable_business_endpoint: {
    inference_key: 'guessable_business_endpoint',
    impact_category: 'revenue_loss',
    cause: 'Business-critical commerce actions reachable through predictable paths',
    effect: 'Predictable URL patterns for order management, billing, and account actions enable automated probing and business-logic manipulation — the foundation for IDOR attacks and commerce fraud',
    high: { min: 0.08, max: 0.25 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  alternate_pricing_safeguard_bypass: {
    inference_key: 'alternate_pricing_safeguard_bypass',
    impact_category: 'revenue_loss',
    cause: 'Alternate commercial actions bypass intended pricing safeguards',
    effect: 'Legacy, beta, or parameter-variant checkout paths process transactions with weaker validation — the weakest pricing path becomes the effective price floor for anyone who discovers it',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  js_discovered_purchase_variant: {
    inference_key: 'js_discovered_purchase_variant',
    impact_category: 'revenue_loss',
    cause: 'Hidden purchase paths operating outside the main safeguard model',
    effect: 'Client-side commerce routes not visible through normal navigation escape trust signals, measurement infrastructure, and server-side validation — revenue through these paths is both unprotected and invisible',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  dynamic_route_weak_control: {
    inference_key: 'dynamic_route_weak_control',
    impact_category: 'revenue_loss',
    cause: 'Deeper commerce logic governed more weakly than the visible purchase flow',
    effect: 'Commerce logic discovered through deep crawling lacks safeguards proportional to the primary flow — creating a gradient of decreasing protection that automated tools exploit preferentially',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  hidden_support_burden: {
    inference_key: 'hidden_support_burden',
    impact_category: 'chargeback_risk',
    cause: 'Hidden support actions increase burden instead of reducing hesitation',
    effect: 'Support infrastructure exists but is structurally disconnected from the buying path — buyers cannot find help during purchase but the same routes generate post-purchase ticket volume, costing support without converting hesitant buyers',
    high: { min: 0.03, max: 0.10 },
    medium: { min: 0.01, max: 0.05 },
    low: { min: 0.005, max: 0.02 },
    base_metric: 'chargeback_rate',
  },
  alternate_variant_control_breakdown: {
    inference_key: 'alternate_variant_control_breakdown',
    impact_category: 'revenue_loss',
    cause: 'Trust, measurement, and pricing controls break on alternate commerce variants',
    effect: 'Alternate commerce variants simultaneously lack pricing safeguards, analytics coverage, and trust signals — pricing can be manipulated, the manipulation is invisible, and the buyer experience lacks trust signals to offset the weaker controls',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  deep_commerce_exploitation_risk: {
    inference_key: 'deep_commerce_exploitation_risk',
    impact_category: 'revenue_loss',
    cause: 'Deeply reachable commerce surfaces easier to exploit than the primary flow',
    effect: 'Guessable endpoints, exposed business logic, and safeguard bypass routes compound to create deep commerce surfaces that are materially weaker than the visible checkout — automated fraud tools target exactly this gradient of decreasing protection',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Phase 2D: Network analysis findings ────

  checkout_api_latency_degraded: {
    inference_key: 'checkout_api_latency_degraded',
    impact_category: 'conversion_loss',
    cause: 'Checkout API latency degrading purchase completion',
    effect: 'Payment-critical API responses exceed acceptable latency on checkout surfaces — every second of checkout latency drives progressive abandonment at the moment of purchase commitment',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  commercial_pages_slow: {
    inference_key: 'commercial_pages_slow',
    impact_category: 'conversion_loss',
    cause: 'Critical commerce pages slower than the rest of the site',
    effect: 'Revenue-generating pages are disproportionately slower than the rest of the site — visitors browse at normal speed but hit friction at the moment they try to convert',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  paid_landing_overloaded: {
    inference_key: 'paid_landing_overloaded',
    impact_category: 'traffic_waste',
    cause: 'Paid landing overloaded before buyers reach the first meaningful action',
    effect: 'Heavy third-party runtime on landing pages wastes paid traffic — media spend arrives into a page that cannot present the offer quickly enough to capture intent, increasing effective CAC',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  third_party_weight_delays_trust: {
    inference_key: 'third_party_weight_delays_trust',
    impact_category: 'conversion_loss',
    cause: 'Third-party request weight delaying the moment of trust and intent',
    effect: 'Non-essential external dependency chains consume bandwidth and execution time before buyers reach confidence — widening the gap between intent arrival and trust formation',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  checkout_brittle_third_party: {
    inference_key: 'checkout_brittle_third_party',
    impact_category: 'revenue_loss',
    cause: 'Checkout reliability depends on brittle third-party services',
    effect: 'Purchase completion depends on external services that fail or respond unreliably — every affected session is a potential lost transaction due to operational fragility at the revenue-critical surface',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  purchase_blocked_failing_requests: {
    inference_key: 'purchase_blocked_failing_requests',
    impact_category: 'revenue_loss',
    cause: 'Purchase flow blocked by failing third-party requests',
    effect: 'Payment or commerce API requests are actively failing on purchase surfaces — buyers who reach checkout and attempt to purchase are being blocked by requests that return errors or never complete',
    high: { min: 0.12, max: 0.35 },
    medium: { min: 0.06, max: 0.18 },
    low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  measurement_breaks_revenue_path: {
    inference_key: 'measurement_breaks_revenue_path',
    impact_category: 'traffic_waste',
    cause: 'Measurement continuity breaks on the path that generates revenue',
    effect: 'Analytics requests failing at runtime on revenue-generating pages — conversion data, attribution, and funnel metrics silently dropping on the surfaces that matter most for optimization',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  purchase_before_deps_ready: {
    inference_key: 'purchase_before_deps_ready',
    impact_category: 'conversion_loss',
    cause: 'Buyers reach the purchase moment before critical dependencies are ready',
    effect: 'Payment and trust dependencies take too long to become available — buyers can interact with the purchase UI before the infrastructure that supports it is ready, leading to failed transactions and missing trust signals',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  trust_assets_late_load: {
    inference_key: 'trust_assets_late_load',
    impact_category: 'conversion_loss',
    cause: 'Trust and reassurance assets load too late to calm hesitation',
    effect: 'Support chat, review widgets, and trust badges load well after the page is interactive — buyers form their trust impression before reassurance arrives, making the investment in trust infrastructure wasted',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  mobile_heavy_runtime_chain: {
    inference_key: 'mobile_heavy_runtime_chain',
    impact_category: 'conversion_loss',
    cause: 'Mobile commerce path degraded by heavy runtime dependency chain',
    effect: 'Mobile connections carry the same third-party weight that is tolerable on desktop — but mobile bandwidth and processing constraints make it conversion-killing, wasting media spend directed at mobile audiences',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  mobile_trust_payment_deps_failing: {
    inference_key: 'mobile_trust_payment_deps_failing',
    impact_category: 'revenue_loss',
    cause: 'Support, payment, or trust layers fail on mobile-first sessions',
    effect: 'Payment SDKs, support widgets, and measurement scripts fail on mobile commercial surfaces — the majority of traffic enters a weaker operational environment than desktop, with fewer working trust signals',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  trust_surfaces_unstable_deps: {
    inference_key: 'trust_surfaces_unstable_deps',
    impact_category: 'conversion_loss',
    cause: 'Trust-critical surfaces rely on unstable external dependencies',
    effect: 'Support widgets, review badges, and trust signals depend on external services that fail or degrade — trust infrastructure becomes invisible during outages exactly when it matters most for reducing hesitation',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },

  // ── Phase 3E: Discoverability findings ────

  commercial_pages_weak_search_representation: {
    inference_key: 'commercial_pages_weak_search_representation',
    impact_category: 'traffic_waste',
    cause: 'High-intent pages not properly represented in search surfaces',
    effect: 'Missing or thin titles and descriptions on commercial pages reduce click-through from search results — discoverable demand exists but never reaches the site',
    high: { min: 0.08, max: 0.20 },
    medium: { min: 0.04, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  social_previews_fail_commercial_value: {
    inference_key: 'social_previews_fail_commercial_value',
    impact_category: 'traffic_waste',
    cause: 'Shared links fail to communicate commercial value',
    effect: 'Commercial pages shared via social or messaging appear as bare URLs without product images or descriptions — every share that fails to communicate value is a wasted distribution opportunity',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  brand_inconsistent_across_surfaces: {
    inference_key: 'brand_inconsistent_across_surfaces',
    impact_category: 'conversion_loss',
    cause: 'Brand appears inconsistently across search and sharing surfaces',
    effect: 'Inconsistent titles and brand presence across search results reduce recognition and click-through — buyers see an unreliable brand presence that suppresses trust before they even reach the site',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  commercial_pages_unlikely_indexed: {
    inference_key: 'commercial_pages_unlikely_indexed',
    impact_category: 'traffic_waste',
    cause: 'Commercial pages unlikely to be reliably indexed',
    effect: 'Revenue-generating pages have missing canonical URLs or noindex directives — search engines may exclude them entirely, making demand for these products invisible',
    high: { min: 0.10, max: 0.30 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  weak_semantic_intent_signals: {
    inference_key: 'weak_semantic_intent_signals',
    impact_category: 'traffic_waste',
    cause: 'Search and AI systems receive weak signals about page purpose',
    effect: 'Without structured data, ranking algorithms and AI assistants must guess page purpose from raw HTML — resulting in lower ranking for commercial queries and inaccurate AI summaries',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  previews_disconnected_from_conversion: {
    inference_key: 'previews_disconnected_from_conversion',
    impact_category: 'conversion_loss',
    cause: 'Social and search previews disconnected from conversion intent',
    effect: 'Preview content that doesn\'t match actual page content creates expectation mismatch — visitors arrive and immediately bounce, converting traffic acquisition cost into waste',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  commercial_pages_not_exposed_for_discovery: {
    inference_key: 'commercial_pages_not_exposed_for_discovery',
    impact_category: 'traffic_waste',
    cause: 'Key commercial pages not structurally exposed for discovery',
    effect: 'Commercial pages with zero internal links are invisible to search crawlers — organic demand for the products or services cannot find the site through search',
    high: { min: 0.08, max: 0.25 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Phase 3E: Brand integrity findings ────

  lookalike_domain_competing_for_traffic: {
    inference_key: 'lookalike_domain_competing_for_traffic',
    impact_category: 'traffic_waste',
    cause: 'Lookalike domains competing for brand traffic',
    effect: 'Active lookalike domains intercept brand traffic — inflating effective customer acquisition cost as brand awareness is captured by competitors or fraudsters',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  external_sites_mimicking_brand: {
    inference_key: 'external_sites_mimicking_brand',
    impact_category: 'revenue_loss',
    cause: 'External sites mimicking brand identity',
    effect: 'Active content mimicry surfaces designed to look like the brand — customers may share payment information with fraudsters, creating chargebacks, legal liability, and lasting trust damage',
    high: { min: 0.08, max: 0.22 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  brand_traffic_exposed_to_deceptive_surfaces: {
    inference_key: 'brand_traffic_exposed_to_deceptive_surfaces',
    impact_category: 'traffic_waste',
    cause: 'Brand traffic exposed to deceptive landing surfaces',
    effect: 'Typosquat domains capture mistyped brand URLs — diverting direct-type traffic and creating fraud exposure when impostor sites process transactions',
    high: { min: 0.04, max: 0.12 },
    medium: { min: 0.02, max: 0.06 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  suspicious_domains_capturing_purchase_intent: {
    inference_key: 'suspicious_domains_capturing_purchase_intent',
    impact_category: 'revenue_loss',
    cause: 'Suspicious domains positioned to capture purchase intent',
    effect: 'Lookalike domains with active commerce patterns process transactions under brand-similar identity — direct revenue leakage from customers who intended to buy from the brand',
    high: { min: 0.06, max: 0.18 },
    medium: { min: 0.03, max: 0.10 },
    low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  customers_exposed_to_phishing_surfaces: {
    inference_key: 'customers_exposed_to_phishing_surfaces',
    impact_category: 'revenue_loss',
    cause: 'Customers exposed to potential phishing surfaces',
    effect: 'High-confidence phishing surfaces combine brand similarity with commerce mimicry — downstream chargebacks, legal liability from data breach, and lasting trust damage when customers learn they were deceived',
    high: { min: 0.08, max: 0.25 },
    medium: { min: 0.04, max: 0.12 },
    low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  brand_presence_diluted_across_variants: {
    inference_key: 'brand_presence_diluted_across_variants',
    impact_category: 'traffic_waste',
    cause: 'Brand presence diluted across competing domain variants',
    effect: 'Ranking signals split across multiple brand-similar domains — reducing organic visibility for the legitimate site and suppressing click-through when buyers cannot identify which domain is real',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.08 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },

  // ── Phase 4B: Behavioral intelligence findings ────

  policy_view_then_abandonment: {
    inference_key: 'policy_view_then_abandonment', impact_category: 'chargeback_risk',
    cause: 'Users drop off after opening refund or return policies',
    effect: 'Policy content is triggering doubt rather than building confidence — buyers read return terms and decide not to buy, or file disputes later because they feel uncertain about recourse',
    high: { min: 0.04, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },
  high_intent_detour_before_abandonment: {
    inference_key: 'high_intent_detour_before_abandonment', impact_category: 'conversion_loss',
    cause: 'High-intent sessions detour into reassurance content before abandonment',
    effect: 'Buyers who reached checkout detour to FAQ, support, or policy before abandoning — high-intent traffic that failed to convert because reassurance was not embedded in the purchase experience',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  support_discovered_too_late_to_convert: {
    inference_key: 'support_discovered_too_late_to_convert', impact_category: 'conversion_loss',
    cause: 'Support is being discovered too late to save the conversion',
    effect: 'Support channels found only after checkout — by the time buyers find help, their hesitation has already driven abandonment. Earlier support visibility could have resolved pre-purchase questions',
    high: { min: 0.04, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  cta_visible_but_behaviorally_dead: {
    inference_key: 'cta_visible_but_behaviorally_dead', impact_category: 'conversion_loss',
    cause: 'Commercial CTA is visible but behaviorally dead',
    effect: 'Users see commercial CTAs but do not click — the call-to-action fails to motivate progression despite being visually present. Conversion opportunity exists but is not captured by the current CTA',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  purchase_hesitation_with_backtrack: {
    inference_key: 'purchase_hesitation_with_backtrack', impact_category: 'conversion_loss',
    cause: 'Users hesitate on the purchase step and backtrack into trust content',
    effect: 'Buyers reach a commercial step and retreat — indicating hesitation at the moment of commitment that could be resolved by stronger trust reinforcement or price justification',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  critical_step_retries_before_abandonment: {
    inference_key: 'critical_step_retries_before_abandonment', impact_category: 'conversion_loss',
    cause: 'Critical commercial step triggers repeated retries before abandonment',
    effect: 'Users repeatedly attempt the same step before giving up — encountering errors or confusion that blocks progression. Each retry is a user fighting the interface before losing patience',
    high: { min: 0.10, max: 0.30 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  mobile_fails_first_commercial_action: {
    inference_key: 'mobile_fails_first_commercial_action', impact_category: 'revenue_loss',
    cause: 'Mobile users fail to progress past the first commercial action',
    effect: 'Mobile entry point to the commercial flow is broken or unusable — the majority of traffic hits a dead end before the commercial journey begins, wasting all upstream acquisition spend',
    high: { min: 0.12, max: 0.30 }, medium: { min: 0.06, max: 0.18 }, low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  funnel_step_alive_but_not_advancing: {
    inference_key: 'funnel_step_alive_but_not_advancing', impact_category: 'conversion_loss',
    cause: 'Funnel step is alive but not advancing sessions',
    effect: 'Active funnel steps fail to advance users to the next step — behavioral dead ends that block the entire downstream funnel despite receiving traffic',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── Phase 4B Hardening: 12 new behavioral findings ────

  hesitation_before_conversion_missing_trust: {
    inference_key: 'hesitation_before_conversion_missing_trust', impact_category: 'conversion_loss',
    cause: 'Users hesitate before conversion due to missing trust signals near CTA',
    effect: 'Hesitation pauses before commercial CTAs indicate buyers want to proceed but lack confidence — every hesitation is a conversion at risk of abandonment due to absent trust reinforcement at the decision point',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  pricing_hesitation_unclear_value: {
    inference_key: 'pricing_hesitation_unclear_value', impact_category: 'conversion_loss',
    cause: 'Users delay conversion after viewing pricing due to unclear value justification',
    effect: 'Pricing creates a decision moment the value proposition fails to carry — users see the price, backtrack to seek justification, and abandon when the product context does not resolve the gap',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  policy_detour_before_conversion: {
    inference_key: 'policy_detour_before_conversion', impact_category: 'conversion_loss',
    cause: 'Users open policies before converting due to trust uncertainty',
    effect: 'Pre-conversion policy detours indicate trust uncertainty at the commitment moment — each detour risks abandonment as users leave the conversion flow to verify terms they should already feel confident about',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  cta_viewed_not_engaged: {
    inference_key: 'cta_viewed_not_engaged', impact_category: 'conversion_loss',
    cause: 'Primary CTA is viewed but not engaged',
    effect: 'The primary action is behaviorally visible but fails to generate clicks — weak positioning, unclear copy, or insufficient context suppress conversion on every session that sees the CTA',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.05, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  sensitive_input_abandonment: {
    inference_key: 'sensitive_input_abandonment', impact_category: 'conversion_loss',
    cause: 'Users abandon after interacting with sensitive input',
    effect: 'Sensitive data requests trigger abandonment when trust context is insufficient — users begin entering data but drop off when the perceived risk exceeds the trust signals present on the surface',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  form_excessive_fields_before_conversion: {
    inference_key: 'form_excessive_fields_before_conversion', impact_category: 'conversion_loss',
    cause: 'Form requires high-effort input before conversion',
    effect: 'Conversion-proximate forms demand disproportionate data collection — each additional field reduces completion rate, and sensitive fields without trust context accelerate abandonment',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  form_submission_retry_friction: {
    inference_key: 'form_submission_retry_friction', impact_category: 'conversion_loss',
    cause: 'Users retry form submission multiple times',
    effect: 'Poor validation feedback or broken submission handling forces users to retry — each attempt erodes confidence and patience, directly reducing form completion rates on conversion-critical surfaces',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  surface_oscillation_before_dropoff: {
    inference_key: 'surface_oscillation_before_dropoff', impact_category: 'conversion_loss',
    cause: 'Back-and-forth between surfaces before dropoff',
    effect: 'Unresolved decision friction causes navigational loops between surfaces — the decisive question is not answered by either surface, ending in abandonment after repeated oscillation',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  conversion_final_step_retry: {
    inference_key: 'conversion_final_step_retry', impact_category: 'revenue_loss',
    cause: 'Conversion attempts require multiple retries in final steps',
    effect: 'Friction at the highest-value funnel step forces repeated attempts — each failed submission erodes buyer confidence, and accumulated failures cause abandonment at the moment revenue is captured',
    high: { min: 0.10, max: 0.30 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  cta_late_availability_delays_action: {
    inference_key: 'cta_late_availability_delays_action', impact_category: 'conversion_loss',
    cause: 'Primary CTA renders late on high-intent surfaces',
    effect: 'Users arrive with intent but the action is unavailable — late rendering widens the window for distraction and hesitation, suppressing the conversion rate on every high-intent session',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  checkout_abandon_no_feedback: {
    inference_key: 'checkout_abandon_no_feedback', impact_category: 'revenue_loss',
    cause: 'Users abandon after initiating checkout due to lack of immediate feedback',
    effect: 'Absent immediate feedback after checkout initiation creates uncertainty — users do not know if the system received their action, causing abandonment at the highest-value moment in the funnel',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  sensitive_input_perceived_risk_dropoff: {
    inference_key: 'sensitive_input_perceived_risk_dropoff', impact_category: 'conversion_loss',
    cause: 'Users drop off after entering sensitive information due to perceived risk',
    effect: 'Trust-to-sensitivity mismatch causes immediate dropoff — users begin entering payment or identity data but the trust signals present are insufficient for the sensitivity of the data requested',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── First Impression Revenue (pixel-dependent) ──
  first_session_milestone_stall: {
    inference_key: 'first_session_milestone_stall', impact_category: 'conversion_loss',
    cause: 'First-time visitors stall before expressing purchase intent',
    effect: 'New visitors never reach commercial surfaces — acquisition spend wasted on sessions that stall at awareness',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  first_session_trust_barrier: {
    inference_key: 'first_session_trust_barrier', impact_category: 'conversion_loss',
    cause: 'First-time visitors hesitate significantly more than returning visitors',
    effect: 'Trust deficit for newcomers blocks conversion — brand familiarity gap not compensated by on-page trust signals',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  first_session_cta_timing_gap: {
    inference_key: 'first_session_cta_timing_gap', impact_category: 'conversion_loss',
    cause: 'First-time visitors take much longer to reach commercial actions',
    effect: 'Commercial entry points optimized for returning visitors — newcomers wander before finding the conversion path',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },

  // ── Action Value Map (pixel-dependent) ──
  low_value_action_dominates: {
    inference_key: 'low_value_action_dominates', impact_category: 'conversion_loss',
    cause: 'Most visible user actions have very low conversion correlation',
    effect: 'User attention directed toward non-revenue actions — high-value conversion paths are overshadowed',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  high_value_action_underexposed: {
    inference_key: 'high_value_action_underexposed', impact_category: 'conversion_loss',
    cause: 'Revenue-positive actions are not visible or compelling enough',
    effect: 'Conversions happen despite UX, not because of it — increasing CTA visibility would amplify revenue',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  dead_weight_surface_traffic: {
    inference_key: 'dead_weight_surface_traffic', impact_category: 'traffic_waste',
    cause: 'Surfaces receive traffic but never advance visitors toward conversion',
    effect: 'Dead-weight pageviews consume resources and ad spend without contributing to revenue progression',
    high: { min: 0.10, max: 0.30 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Acquisition Integrity (pixel-dependent) ──
  paid_traffic_friction_elevated: {
    inference_key: 'paid_traffic_friction_elevated', impact_category: 'conversion_loss',
    cause: 'Paid traffic encounters significantly more friction than organic',
    effect: 'Ad spend directed toward visitors who face disproportionate obstacles — landing experience not aligned with ad promise',
    high: { min: 0.12, max: 0.30 }, medium: { min: 0.06, max: 0.18 }, low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  paid_traffic_trust_gap: {
    inference_key: 'paid_traffic_trust_gap', impact_category: 'conversion_loss',
    cause: 'Paid visitors show more trust-seeking behavior than organic visitors',
    effect: 'Paid visitors lack brand familiarity — site fails to compensate for the inherent trust deficit of ad-driven traffic',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  paid_mobile_compounding_waste: {
    inference_key: 'paid_mobile_compounding_waste', impact_category: 'conversion_loss',
    cause: 'Paid + mobile traffic compounds two friction sources simultaneously',
    effect: 'The highest-waste segment — trust gap from paid traffic plus UX friction from mobile experience stack multiplicatively',
    high: { min: 0.15, max: 0.35 }, medium: { min: 0.08, max: 0.20 }, low: { min: 0.04, max: 0.10 },
    base_metric: 'revenue',
  },

  // ── Mobile Revenue Exposure (pixel-dependent) ──
  mobile_conversion_gap: {
    inference_key: 'mobile_conversion_gap', impact_category: 'conversion_loss',
    cause: 'Mobile converts at a significantly lower rate than desktop',
    effect: 'Trapped mobile revenue — visitors who would convert on desktop cannot on mobile due to form friction, CTA timing, or layout issues',
    high: { min: 0.12, max: 0.30 }, medium: { min: 0.06, max: 0.18 }, low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  mobile_form_friction_elevated: {
    inference_key: 'mobile_form_friction_elevated', impact_category: 'conversion_loss',
    cause: 'Mobile users retry form submissions at a significantly higher rate',
    effect: 'Forms that work on desktop create friction on mobile — each retry is a moment of potential abandonment',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  mobile_cta_timing_degraded: {
    inference_key: 'mobile_cta_timing_degraded', impact_category: 'conversion_loss',
    cause: 'Primary CTAs render significantly later on mobile than desktop',
    effect: 'On mobile where attention spans are shorter, late-rendering CTAs may never be seen or appear after the user has already decided to leave',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },

  // ── Friction Tax (pixel-dependent) ──
  funnel_step_friction_cost: {
    inference_key: 'funnel_step_friction_cost', impact_category: 'conversion_loss',
    cause: 'Combined UX friction (hesitation, retries, oscillation) across funnel steps',
    effect: 'The "friction tax" — measurable cost of behavioral obstacles at each step that block otherwise willing buyers',
    high: { min: 0.10, max: 0.28 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },
  oscillation_decision_cost: {
    inference_key: 'oscillation_decision_cost', impact_category: 'conversion_loss',
    cause: 'Users oscillate between surfaces unable to make purchase decisions',
    effect: 'Back-and-forth navigation indicates unresolved questions — each oscillation loop increases abandonment probability',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  checkout_entry_friction: {
    inference_key: 'checkout_entry_friction', impact_category: 'conversion_loss',
    cause: 'Large gap between sessions expressing intent and reaching checkout',
    effect: 'The conversion gate blocks intent — users want to buy but something between intent and checkout stops them',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.05, max: 0.15 }, low: { min: 0.02, max: 0.06 },
    base_metric: 'revenue',
  },

  // ── Trust Revenue Gap (pixel-dependent) ──
  trust_deficit_conversion_drag: {
    inference_key: 'trust_deficit_conversion_drag', impact_category: 'conversion_loss',
    cause: 'Trust-deficit sessions have drastically lower conversion rates',
    effect: 'Revenue gap between trust-confident and trust-deficit sessions represents recoverable revenue if trust barriers are addressed',
    high: { min: 0.12, max: 0.30 }, medium: { min: 0.06, max: 0.18 }, low: { min: 0.03, max: 0.08 },
    base_metric: 'revenue',
  },
  reassurance_seeking_elevated: {
    inference_key: 'reassurance_seeking_elevated', impact_category: 'conversion_loss',
    cause: 'High percentage of sessions actively seek reassurance before buying',
    effect: 'Trust is not embedded in the commercial flow — users must leave the conversion path to find reassurance and many do not return',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  sensitive_input_trust_gap: {
    inference_key: 'sensitive_input_trust_gap', impact_category: 'conversion_loss',
    cause: 'Sessions abandon at sensitive form fields at an elevated rate',
    effect: 'Users reach data entry and decide the risk exceeds the value — surrounding trust context insufficient for data sensitivity',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── Path to Purchase Efficiency (pixel-dependent) ──
  path_length_exceeds_efficient: {
    inference_key: 'path_length_exceeds_efficient', impact_category: 'conversion_loss',
    cause: 'Visitors wander through too many surfaces before converting or abandoning',
    effect: 'Every additional page between awareness and conversion is an opportunity for intent decay and distraction',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  intent_absorber_detected: {
    inference_key: 'intent_absorber_detected', impact_category: 'conversion_loss',
    cause: 'Specific surfaces absorb purchase intent rather than advancing it',
    effect: 'Users visit these surfaces and lose momentum — intent gets diluted by information overload or missing CTAs',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  intent_decay_time_excessive: {
    inference_key: 'intent_decay_time_excessive', impact_category: 'conversion_loss',
    cause: 'Excessive time between intent expressed and conversion start',
    effect: 'Purchase intent decays over time — long decision paths lose buyers who would otherwise convert',
    high: { min: 0.08, max: 0.22 }, medium: { min: 0.04, max: 0.12 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── Wave 3.3: Security posture (money_moment_exposure) ──
  security_header_weakness: {
    inference_key: 'security_header_weakness', impact_category: 'conversion_loss',
    cause: 'Browsers signal your site as unsafe to buyers',
    effect: 'Without HSTS and CSP, browsers show "Not Secure" warnings, remove the padlock icon, and allow script injection — buyers see these signals and abandon before purchasing',
    high: { min: 0.03, max: 0.08 }, medium: { min: 0.01, max: 0.03 }, low: { min: 0.005, max: 0.01 },
    base_metric: 'revenue',
  },
  mixed_content_exposure: {
    inference_key: 'mixed_content_exposure', impact_category: 'conversion_loss',
    cause: 'Checkout silently breaks for some visitors',
    effect: 'Payment scripts, form submissions, and trust badges loaded over HTTP are silently blocked by the browser on HTTPS pages — the buyer clicks Pay and nothing happens',
    high: { min: 0.05, max: 0.15 }, medium: { min: 0.02, max: 0.05 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  sensitive_endpoint_exposed: {
    inference_key: 'sensitive_endpoint_exposed', impact_category: 'revenue_loss',
    cause: 'Infrastructure credentials are one search away from compromise',
    effect: 'Publicly accessible .env files, database backups, and admin panels give attackers everything needed to take over commerce operations — a breach shuts down revenue entirely',
    high: { min: 0.05, max: 0.15 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  // Wave 3.3 expansion: cybersecurity pack
  checkout_script_hijack_risk: {
    inference_key: 'checkout_script_hijack_risk', impact_category: 'conversion_loss',
    cause: 'Your checkout can be hijacked by compromised scripts',
    effect: 'Unvetted external scripts on payment pages without CSP can silently replace payment forms, redirect card data, or inject fake checkout flows — buyers trust your domain while attackers capture their payment details',
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.03, max: 0.08 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  buyer_session_theft_risk: {
    inference_key: 'buyer_session_theft_risk', impact_category: 'revenue_loss',
    cause: 'Buyer sessions can be stolen on your commercial pages',
    effect: 'Cookies on commercial pages lacking Secure, HttpOnly, or SameSite flags allow attackers to steal buyer sessions via XSS or network sniffing, make purchases with saved payment methods, or access account data',
    high: { min: 0.05, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  checkout_clickjack_risk: {
    inference_key: 'checkout_clickjack_risk', impact_category: 'conversion_loss',
    cause: 'Your checkout page can be faked inside another site',
    effect: 'Missing clickjack protection on commercial pages allows attackers to embed your checkout in an invisible iframe inside a fake site — buyers authorize payments thinking they are on a different page',
    high: { min: 0.06, max: 0.15 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  error_page_information_leak: {
    inference_key: 'error_page_information_leak', impact_category: 'revenue_loss',
    cause: 'Error pages expose internal system architecture to anyone',
    effect: 'Verbose error responses with stack traces, database details, and framework versions give attackers a roadmap — targeted attacks become trivial instead of opportunistic',
    high: { min: 0.03, max: 0.08 }, medium: { min: 0.01, max: 0.04 }, low: { min: 0.005, max: 0.01 },
    base_metric: 'revenue',
  },
  payment_data_unencrypted: {
    inference_key: 'payment_data_unencrypted', impact_category: 'revenue_loss',
    cause: 'Payment data crosses an unencrypted boundary',
    effect: 'Payment forms submitting to insecure HTTP or untrusted external destinations expose card numbers, CVVs, and personal data to any network observer — from coffee shop WiFi to compromised routers',
    high: { min: 0.10, max: 0.25 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.01, max: 0.04 },
    base_metric: 'revenue',
  },
  // Wave 3.3 expansion: cybersecurity pack (batch 2)
  email_deliverability_risk: {
    inference_key: 'email_deliverability_risk', impact_category: 'chargeback_risk',
    cause: 'Order confirmation emails may not reach buyers',
    effect: 'Without SPF/DKIM/DMARC, transactional emails land in spam — buyers assume fraud and file chargebacks',
    high: { min: 0.04, max: 0.10 }, medium: { min: 0.02, max: 0.05 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  cors_misconfiguration_risk: {
    inference_key: 'cors_misconfiguration_risk', impact_category: 'revenue_loss',
    cause: 'Any website can make authenticated requests to your checkout',
    effect: 'Wildcard CORS on payment endpoints lets malicious sites read session data, initiate purchases, and extract customer information',
    high: { min: 0.05, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  rate_limiting_absent_on_commerce: {
    inference_key: 'rate_limiting_absent_on_commerce', impact_category: 'revenue_loss',
    cause: 'Commercial endpoints accept unlimited automated requests',
    effect: 'Without rate limiting, bots can test thousands of stolen cards per minute, hoard inventory, and scrape pricing — generating chargebacks and operational chaos',
    high: { min: 0.06, max: 0.15 }, medium: { min: 0.03, max: 0.08 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  predictable_order_urls: {
    inference_key: 'predictable_order_urls', impact_category: 'revenue_loss',
    cause: 'Customer order and account data is accessible via predictable URLs',
    effect: 'Sequential URLs like /order/123 let anyone enumerate orders, invoices, and customer profiles — exposing personal and financial data at scale',
    high: { min: 0.05, max: 0.15 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },

  // ── Wave 3.1 Tier 2: LLM enrichment findings ──────────
  social_proof_generic: {
    inference_key: 'social_proof_generic', impact_category: 'conversion_loss',
    cause: 'Testimonials are generic and unattributed',
    effect: "Reviews like 'Great product!' without a name, company, or measurable outcome reduce trust instead of building it — buyers question if the reviews are real",
    high: { min: 0.03, max: 0.08 }, medium: { min: 0.01, max: 0.04 }, low: { min: 0.005, max: 0.02 },
    base_metric: 'revenue',
  },
  form_error_messages_unhelpful: {
    inference_key: 'form_error_messages_unhelpful', impact_category: 'conversion_loss',
    cause: 'Form error messages are technical instead of helpful',
    effect: "When a buyer enters an invalid email and sees 'Invalid input' instead of 'Please enter a valid email (e.g. name@example.com)', they don't know what to fix and abandon the form",
    high: { min: 0.04, max: 0.10 }, medium: { min: 0.02, max: 0.05 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  onboarding_no_quick_win: {
    inference_key: 'onboarding_no_quick_win', impact_category: 'conversion_loss',
    cause: 'New users don\'t experience product value in the first session',
    effect: "Without a quick win in the first minutes — a visible result, a completed setup, a personalized recommendation — trial users conclude the product isn't for them and never return",
    high: { min: 0.08, max: 0.20 }, medium: { min: 0.04, max: 0.10 }, low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },

  // ── Tier 1 Copy Analysis ──────────────────────
  checkout_trust_language_absent: {
    inference_key: 'checkout_trust_language_absent', impact_category: 'conversion_loss',
    cause: "Your checkout doesn't tell the buyer it's safe to purchase",
    effect: 'Checkout pages without security language, guarantees, or social proof leave buyers anxious at the payment moment — the absence of reassurance directly suppresses conversion at the highest-intent step',
    high: { min: 0.05, max: 0.15 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  cta_clarity_weak_on_commercial: {
    inference_key: 'cta_clarity_weak_on_commercial', impact_category: 'conversion_loss',
    cause: 'Your buttons compete with each other and none convinces',
    effect: 'Competing, generic, or unclear CTAs on commercial pages leave visitors unsure what to do next — when every button competes equally, none wins the click and conversion stalls',
    high: { min: 0.06, max: 0.18 }, medium: { min: 0.03, max: 0.08 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  product_page_copy_generic: {
    inference_key: 'product_page_copy_generic', impact_category: 'conversion_loss',
    cause: 'Your product pages use generic supplier text',
    effect: 'Manufacturer-standard descriptions fail to differentiate, address objections, or communicate benefits — buyers comparison-shop and leave because every store says the same thing',
    high: { min: 0.05, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  pricing_page_framing_unclear: {
    inference_key: 'pricing_page_framing_unclear', impact_category: 'conversion_loss',
    cause: "Your visitor doesn't know which plan to choose",
    effect: 'When the recommended plan is unclear, features are listed without value framing, and objections are unaddressed — visitors stall at plan selection because they cannot decide',
    high: { min: 0.04, max: 0.12 }, medium: { min: 0.02, max: 0.06 }, low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },

  // ── Phase 4A: Commerce context (Shopify-powered) ──
  checkout_abandonment_revenue_leak: {
    inference_key: 'checkout_abandonment_revenue_leak',
    impact_category: 'revenue_loss',
    cause: 'Your checkout loses money every time a buyer walks away',
    effect: 'Buyers who reach checkout and abandon represent the highest-intent traffic that failed to convert — the gap between abandonment rate and industry benchmark is direct recoverable revenue',
    high: { min: 0.10, max: 0.15 }, medium: { min: 0.07, max: 0.10 }, low: { min: 0.05, max: 0.07 },
    base_metric: 'revenue',
  },
  promoted_product_out_of_stock: {
    inference_key: 'promoted_product_out_of_stock',
    impact_category: 'revenue_loss',
    cause: 'Products on your site cannot be bought — out of stock',
    effect: 'Promoted products that are out of stock convert ad spend and organic traffic into dead ends — buyers who arrived ready to purchase leave empty-handed',
    high: { min: 0.02, max: 0.03 }, medium: { min: 0.01, max: 0.02 }, low: { min: 0.01, max: 0.01 },
    base_metric: 'revenue',
  },
  high_refund_rate_eroding_revenue: {
    inference_key: 'high_refund_rate_eroding_revenue',
    impact_category: 'revenue_loss',
    cause: 'Refund rate is eating into your revenue',
    effect: 'Each refund costs the original sale plus processing fees, return shipping, and operational time — a sustained elevated refund rate compounds into material margin erosion',
    high: { min: 0.08, max: 0.12 }, medium: { min: 0.05, max: 0.08 }, low: { min: 0.03, max: 0.05 },
    base_metric: 'revenue',
  },
  single_payment_gateway_risk: {
    inference_key: 'single_payment_gateway_risk',
    impact_category: 'revenue_loss',
    cause: 'One payment gateway outage stops all your revenue',
    effect: 'When a single gateway processes all transactions, any outage, rate limit, or policy change halts revenue completely — the expected annual downtime cost is a function of gateway reliability',
    high: { min: 0.03, max: 0.05 }, medium: { min: 0.02, max: 0.03 }, low: { min: 0.02, max: 0.02 },
    base_metric: 'revenue',
  },
  discount_abuse_pattern: {
    inference_key: 'discount_abuse_pattern',
    impact_category: 'revenue_loss',
    cause: 'Discount overuse is leaking margin on most orders',
    effect: 'When most orders carry a discount, buyers are trained to never pay full price — margin erodes steadily as the effective average order value declines while acquisition costs remain constant',
    high: { min: 0.06, max: 0.08 }, medium: { min: 0.04, max: 0.06 }, low: { min: 0.03, max: 0.04 },
    base_metric: 'revenue',
  },
  ad_spend_platform_concentration_risk: {
    inference_key: 'ad_spend_platform_concentration_risk',
    impact_category: 'revenue_loss',
    cause: 'Most of your ad budget lives on one platform — a single policy change halts acquisition',
    effect: 'When one platform concentrates acquisition spend, any account disable, policy shift, or pricing change halts new-customer inflow while you scramble to stand up an alternative. Competitors on diversified stacks keep acquiring during the gap',
    high: { min: 0.04, max: 0.06 }, medium: { min: 0.03, max: 0.04 }, low: { min: 0.02, max: 0.03 },
    base_metric: 'revenue',
  },
  ads_without_conversion_visibility: {
    inference_key: 'ads_without_conversion_visibility',
    impact_category: 'revenue_loss',
    cause: "You're spending on ads without the commerce data to prove they work",
    effect: 'Ad spend without conversion tracking is capital deployed blind. You cannot compare creatives, cannot shift budget to winners, cannot defend the spend in a board meeting. A fraction of that budget is, statistically, being wasted — you just have no way to find which fraction',
    high: { min: 0.05, max: 0.08 }, medium: { min: 0.03, max: 0.05 }, low: { min: 0.02, max: 0.03 },
    base_metric: 'revenue',
  },
  ad_creative_dead_destination: {
    inference_key: 'ad_creative_dead_destination',
    impact_category: 'revenue_loss',
    cause: 'An ad creative is burning money sending buyers to a page that does not exist',
    effect: 'Every click on this ad ends at a 404, timeout, or broken redirect chain. The buyer cannot complete any action — 100% of the spend on this creative is waste, recoverable immediately by fixing the destination URL',
    high: { min: 0.01, max: 0.03 }, medium: { min: 0.005, max: 0.01 }, low: { min: 0.005, max: 0.005 },
    base_metric: 'revenue',
  },
  ad_creative_landing_trust_gap: {
    inference_key: 'ad_creative_landing_trust_gap',
    impact_category: 'revenue_loss',
    cause: 'An ad sends buyers to collect sensitive data on a page with no visible trust reassurance',
    effect: 'The ad got the click and brought a buyer to the conversion step — but the landing page asks for card or personal data without trust badges, reviews, or security seals. The gap between what the ad promised and what the page reassures drives abandonment at the most critical moment',
    high: { min: 0.04, max: 0.06 }, medium: { min: 0.02, max: 0.04 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  ad_creative_form_friction_waste: {
    inference_key: 'ad_creative_form_friction_waste',
    impact_category: 'revenue_loss',
    cause: 'An ad sends buyers to a form that asks for too much before they can convert',
    effect: 'Every field past six on a conversion form measurably lifts abandonment. The ad brought interested buyers to the final step and the form pushed them away — a fraction of the ad spend converts to friction cost instead of revenue',
    high: { min: 0.03, max: 0.05 }, medium: { min: 0.02, max: 0.03 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  ad_creative_mobile_checkout_degraded: {
    inference_key: 'ad_creative_mobile_checkout_degraded',
    impact_category: 'revenue_loss',
    cause: 'An ad sends mobile buyers to a checkout path that is slow or broken on mobile',
    effect: 'Mobile traffic from this ad hits a degraded experience — CTAs load late, steps fail, or the path stalls. The ad did its job getting the click but the landing page fails to convert it on the device the buyer is using',
    high: { min: 0.03, max: 0.05 }, medium: { min: 0.02, max: 0.03 }, low: { min: 0.01, max: 0.02 },
    base_metric: 'revenue',
  },
  low_repeat_purchase_rate: {
    inference_key: 'low_repeat_purchase_rate',
    impact_category: 'revenue_loss',
    cause: "Buyers aren't coming back — acquisition cost isn't being recovered",
    effect: 'When repeat purchase rate is below benchmark, every customer is effectively a one-time transaction — acquisition cost cannot be amortized, and lifetime value stays capped at the first order',
    high: { min: 0.08, max: 0.12 }, medium: { min: 0.05, max: 0.08 }, low: { min: 0.05, max: 0.05 },
    base_metric: 'revenue',
  },
  dead_weight_products: {
    inference_key: 'dead_weight_products',
    impact_category: 'revenue_loss',
    cause: "Listed products haven't sold in 30 days — dead weight",
    effect: 'Products with zero sales dilute site search, clutter category pages, and waste operational bandwidth — removing or repositioning them frees attention for items that actually convert',
    high: { min: 0.02, max: 0.03 }, medium: { min: 0.01, max: 0.02 }, low: { min: 0.01, max: 0.01 },
    base_metric: 'revenue',
  },
};

// ──────────────────────────────────────────────
// Positive Impact Baselines (retention)
//
// Mirror of IMPACT_BASELINES for positive findings. When an inference
// concludes "this control is in place / this surface is healthy" and
// the inference_key has an entry here, the impact engine emits a
// QuantifiedValueCase with impact_role='retention' and a monetary
// range representing the approximate value the business is keeping
// because the control is working.
//
// These are CONSERVATIVE counterfactuals: "if this control were
// absent, we'd expect the same percentage loss as the corresponding
// IMPACT_BASELINES entry." The math is intentionally symmetric —
// trust_boundary_crossed negative says "10-25% revenue at risk on
// high severity"; trust_boundary_crossed positive (retention) says
// "10-25% revenue retained on high severity."
//
// Phase 1.2 seeds a small starter set. Phase 2.3 populates the rest
// of the catalog as part of the "positive findings with upside"
// content backfill. Inferences without a positive baseline here
// simply don't emit a retention case — they still appear as
// positive findings in the UI, just without a monetary number.
//
// See also: packages/impact/engine.ts — the engine checks this map
// when conclusion_value indicates absence of a problem.
// ──────────────────────────────────────────────

export const POSITIVE_IMPACT_BASELINES: Record<string, BaselineEntry> = {
  // Phase 1.2 starter set — the most common controls that are worth
  // quantifying as retained value. Phase 2.3 expands this.
  trust_boundary_crossed: {
    inference_key: 'trust_boundary_crossed',
    impact_category: 'conversion_loss',
    cause: 'Checkout trust continuity is intact',
    effect: 'Buyers stay on-domain through the purchase moment — trust breaks that typically erode checkout completion are not happening here',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.12 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  policy_gap: {
    inference_key: 'policy_gap',
    impact_category: 'conversion_loss',
    cause: 'Consumer protection policies in place and discoverable',
    effect: 'Privacy, terms, and refund policies are present where buyers look for them — the hesitation typically caused by policy absence is not eroding your conversion',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.07 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'revenue',
  },
  measurement_coverage: {
    inference_key: 'measurement_coverage',
    impact_category: 'traffic_waste',
    cause: 'Measurement infrastructure adequate for optimization',
    effect: 'Ad spend is attributable, conversion funnels are observable, and revenue leakage can be identified — retained optimization leverage that would otherwise be invisible',
    high: { min: 0.10, max: 0.25 },
    medium: { min: 0.05, max: 0.10 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  checkout_integrity: {
    inference_key: 'checkout_integrity',
    impact_category: 'conversion_loss',
    cause: 'Checkout structural integrity holding',
    effect: 'On-domain handoffs, adequate policy coverage, and stable checkout architecture keep completion rate predictable under traffic — the loss pattern typical of degraded integrity is not present',
    high: { min: 0.15, max: 0.35 },
    medium: { min: 0.05, max: 0.15 },
    low: { min: 0.02, max: 0.05 },
    base_metric: 'revenue',
  },
  refund_policy_gap: {
    inference_key: 'refund_policy_gap',
    impact_category: 'chargeback_risk',
    cause: 'Refund policy clear and accessible',
    effect: 'Buyers who would otherwise dispute via their card issuer find a resolution path on your site first — retained chargeback headroom that protects processor standing',
    high: { min: 0.05, max: 0.15 },
    medium: { min: 0.02, max: 0.07 },
    low: { min: 0.01, max: 0.03 },
    base_metric: 'chargeback_rate',
  },
};
